/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EditorialStandardsRouteImport } from './routes/editorial-standards'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ArticlesWhenTheWhistleblowerTookTheMainStageRouteImport } from './routes/articles.when-the-whistleblower-took-the-main-stage'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorialStandardsRoute = EditorialStandardsRouteImport.update({
  id: '/editorial-standards',
  path: '/editorial-standards',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesWhenTheWhistleblowerTookTheMainStageRoute =
  ArticlesWhenTheWhistleblowerTookTheMainStageRouteImport.update({
    id: '/articles/when-the-whistleblower-took-the-main-stage',
    path: '/articles/when-the-whistleblower-took-the-main-stage',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/editorial-standards': typeof EditorialStandardsRoute
  '/privacy': typeof PrivacyRoute
  '/articles/when-the-whistleblower-took-the-main-stage': typeof ArticlesWhenTheWhistleblowerTookTheMainStageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/editorial-standards': typeof EditorialStandardsRoute
  '/privacy': typeof PrivacyRoute
  '/articles/when-the-whistleblower-took-the-main-stage': typeof ArticlesWhenTheWhistleblowerTookTheMainStageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/editorial-standards': typeof EditorialStandardsRoute
  '/privacy': typeof PrivacyRoute
  '/articles/when-the-whistleblower-took-the-main-stage': typeof ArticlesWhenTheWhistleblowerTookTheMainStageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/editorial-standards'
    | '/privacy'
    | '/articles/when-the-whistleblower-took-the-main-stage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/editorial-standards'
    | '/privacy'
    | '/articles/when-the-whistleblower-took-the-main-stage'
  id:
    | '__root__'
    | '/'
    | '/editorial-standards'
    | '/privacy'
    | '/articles/when-the-whistleblower-took-the-main-stage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EditorialStandardsRoute: typeof EditorialStandardsRoute
  PrivacyRoute: typeof PrivacyRoute
  ArticlesWhenTheWhistleblowerTookTheMainStageRoute: typeof ArticlesWhenTheWhistleblowerTookTheMainStageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editorial-standards': {
      id: '/editorial-standards'
      path: '/editorial-standards'
      fullPath: '/editorial-standards'
      preLoaderRoute: typeof EditorialStandardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/when-the-whistleblower-took-the-main-stage': {
      id: '/articles/when-the-whistleblower-took-the-main-stage'
      path: '/articles/when-the-whistleblower-took-the-main-stage'
      fullPath: '/articles/when-the-whistleblower-took-the-main-stage'
      preLoaderRoute: typeof ArticlesWhenTheWhistleblowerTookTheMainStageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EditorialStandardsRoute: EditorialStandardsRoute,
  PrivacyRoute: PrivacyRoute,
  ArticlesWhenTheWhistleblowerTookTheMainStageRoute:
    ArticlesWhenTheWhistleblowerTookTheMainStageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
